config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :projects
  resources :tasks do
    patch :change_status, on: :member
  end
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :project
  belongs_to :status, class_name: 'TaskStatus'

  validates :number, :title, presence: true
  validates :number, numericality: { greater_than: 0 }
  validate :associations_should_have_same_project

  has_rich_text :description

  broadcasts_to ->(task) { [task.project, :tasks] }, template: 'tasks/_table_row'

  def to_param
    return full_number if association(:project).loaded?

    super
  end

  def full_number
    "#{project.code.upcase}-#{number}"
  end

  def self.find_by_full_number_or_id!(number_or_id)
    return find(number_or_id) if number_or_id.is_a?(Numeric) || number_or_id =~ /\A\d+\z/

    project_code, number = number_or_id.split('-')
    project = Project.find_by!(code: project_code.downcase)
    find_by!(project:, number:)
  end

  private

  def associations_should_have_same_project
    return if status&.project == project

    errors.add(:status, "Doesn't belong in the same project")
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :fetch_task, only: %w[show edit update delete change_status]

  def index
    self.current_project = fetch_project
    @tasks = if current_project
               current_project.tasks
             else
               Task.all
             end

    @tasks = @tasks.includes(:status, project: :task_statuses)
  end

  def show; end

  def new
    @project = fetch_project || Project.order(:name).first
    @form = Tasks::Create.new(project_id: @project.id)
  end

  def create
    @form = Tasks::Create.new(params.expect(task: %i[project_id title description status_id]))
    if @form.perform
      redirect_to tasks_path(project: @form.project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @form = Tasks::Update.new(@task.attributes.slice(*Tasks::Update.attribute_names))
  end

  def update
    @form = Tasks::Update.new(params.expect(task: %i[title description status_id]))

    if @form.perform(@task)
      redirect_to task_path(@task)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def delete
    @task.destroy!
    redirect_to tasks_path(project: @task.project)
  end

  def change_status
    @form = Tasks::ChangeStatus.new(params.expect(task: :status_id))

    if @form.perform(@task)
      respond_to do |format|
        format.html { redirect_to task_path(@task) }
        format.turbo_stream
      end
    else
      head :unprocessable_entity
    end
  end

  private

  def fetch_project
    return nil if params[:project].blank?

    Project.find_by!(code: params[:project])
  end

  def fetch_task
    @task = Task.includes(:project).find_by_full_number_or_id!(params[:id])
    self.current_project = @task.project
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
  def tasks_index_title
    return "Tasks for #{current_project.name}" if current_project

    # TODO: add conditions for filters, etc

    'Tasks'
  end

  def task_status_selector(task, with_form: false)
    render Tasks::Statuses::SelectorViewModel.new(task, with_form:)
  end
end

app/views/tasks/_status_selector.html.slim
details.dropdown.task-status-selector id=id data-controller="tasks--status-selector"
  summary= task_status_badge[task.status]
  ul
    - project_task_statuses.each do |status|
      li
        a href="#" data-status-id="#{status.id}" data-action="tasks--status-selector#changeStatus:prevent" = task_status_badge[status]
  - if with_form
    = form_with model: Tasks::ChangeStatus.new, url: change_status_task_path(task), method: :patch, data: {'tasks--status-selector-target': 'form', action: 'turbo:submit-end->tasks--status-selector#finalize'} do |f|
      = f.hidden_field :status_id, data: {'tasks--status-selector-target': 'statusField'}

app/views/tasks/_table_row.html.slim
- cache task do
  tr id="task_#{task.id}"
    td= link_to task.full_number, task_path(task)
    td
      = task_status_selector task, with_form: true
    td= task.title
    td
      = link_to 'Edit', edit_task_path(task)

app/views/tasks/change_status.turbo_stream.slim
- view_model = Tasks::Statuses::SelectorViewModel.new(@task, with_form: true)
= turbo_stream.replace view_model.dom_id, render(view_model)

app/views/tasks/edit.html.slim
h1
  | Editing task
  =< @task.full_number

= form_with model: @form do |form|
  .field
    = form.label :status_id
    = form.select :status_id, current_project.task_statuses.default_order.map { |ts| [ts.name, ts.id] }
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :description
    = form.rich_textarea :description
  .submit
    = form.submit 'Update task'

app/views/tasks/index.html.slim
h1= tasks_index_title

section.row
  = link_to 'New', new_task_path(project: current_project&.code)

table.tasks-table
  thead
  tbody#tasks
    = render partial: 'table_row', collection: @tasks, as: :task

- if current_project
  = turbo_stream_from current_project, :tasks

app/views/tasks/new.html.slim
h1 New task

= form_with model: @form, data: {controller: 'form-projects-selector', 'form-projects-selector-frame-value' => 'status_select'} do |form|
  .field
    = form.label :project_id
    = form.select :project_id, Project.order(:name).map { |p| [p.name, p.id, {'data-code': p.code}] }, {}, data: {action: 'form-projects-selector#changeProject'}
  = turbo_frame_tag :status_select do
    .field
      = form.label :status_id
      = form.select :status_id, TaskStatus.where(project: @form.project).default_order.map { |ts| [ts.name, ts.id] }
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :description
    = form.rich_textarea :description
  .submit
    = form.submit 'Create task'

app/views/tasks/show.html.slim
div
  em= @task.full_number
h1= @task.title

section.task-show-info
  = task_status_selector @task, with_form: true
  = turbo_stream_from @task, :status, :with_form


section= @task.description

section
  ul.links
    li= link_to 'Edit', edit_task_path(@task)