config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :projects
  resources :tasks do
    patch :change_status, on: :member
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  enum :status, %w[preparing ready archived].index_by(&:itself), default: :preparing

  validates :name, :code, :status, presence: true
  validates :code, exclusion: { in: %w[new] }, uniqueness: true, format: { with: /\A[a-z][a-z0-9]{1,}\z/ }

  has_many :tasks, dependent: :restrict_with_exception
  has_many :task_statuses, dependent: :destroy

  has_rich_text :description

  normalizes :code, with: ->(code) { code.strip.downcase.gsub(/\W+/, '') }

  after_commit :schedule_post_init_job, on: :create
  after_destroy_commit :drop_tasks_number_sequence
  after_destroy_commit :broadcast_the_destroy

  def to_param
    return unless id

    code
  end

  def tasks_number_sequence_name
    "_seq_projects__#{code}_tasks_number"
  end

  def next_task_number
    result = self.class.connection.exec_query "SELECT NEXT VALUE FOR #{tasks_number_sequence_name} AS task_number"
    raise "Expected one result, got #{result.count}" unless result.one?

    result.first['task_number']
  end

  private

  def schedule_post_init_job
    Projects::PostInitJob.perform_later id
  end

  def drop_tasks_number_sequence
    self.class.connection.execute "DROP SEQUENCE IF EXISTS #{tasks_number_sequence_name}"
  end

  def broadcast_the_destroy
    broadcast_remove_to Project, :admin_table
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :fetch_project!, only: %w[show edit update destroy]

  def index
    @projects = available_projects
  end

  def show; end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to url_for(action: :index), notice: "Project #{@project.name} being created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy; end

  private

  def available_projects
    Project.ready
  end

  def fetch_project!
    @project = available_projects.find_by!(code: params[:id])
    self.current_project = @project
  end

  def project_params
    params.expect(project: %i[code name description])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.slim
= form_with model: @project do |form|
  .field
    = form.label :code
    = form.text_field :code
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :description
    = form.rich_textarea :description
  .submit
    = form.submit 'Submit'

app/views/projects/_row.html.slim
li id="project_#{project.id}" = link_to project.name, project

app/views/projects/edit.html.slim
h1
  span Editing project
  span= @project.name

= render 'form'

app/views/projects/index.html.slim
.row
  = link_to 'New', new_project_path

/ TODO: admin view, extract when doing roles stuff
ul#projects
  = render collection: @projects, partial: 'row', as: :project

= turbo_stream_from Project, :admin_table

app/views/projects/new.html.slim
h1 New project

= render 'form'

app/views/projects/show.html.slim
h1= @project.name

section
  ul.links
    li= link_to 'Edit', edit_project_path(@project)
    li= link_to 'Tasks', tasks_path(project: @project)

section= @project.description